### PR TITLE
Notebook showing how to use LinearSimulator to generate particle images from a given volume

### PR DESCRIPTION
**Pull request by bogdantoader**
The linear simulator is a differentiable simulator of cryo-EM images that implements the so-called "weak-phase approximation" of the cryo-EM image formation model.

This simulator is a key piece for deep generative models. Being able to explain its use is fundamental for simSPI, which makes this task a high-priority task.

## Checklist

Verify that your PR checks all the following items.

- [x] The pull request (PR) has a clear and explanatory title.
- [x] The description of this PR links to relevant [GitHub issues](https://github.com/compSPI/simSPI/issues).
- [x] Unit tests have been added in the [tests folder](https://github.com/compSPI/simSPI/tree/master/tests):
  - [x] in the `test_*.py files` corresponding the files modified by this PR,
  - [x] for each function added by this PR.
- [x] The code of this PR is properly documented, with [docstrings following simSPI conventions](https://github.com/compspi/compspi/blob/master/docs/contributing.rst#the-anatomy-of-a-docstring).
- [x] The PR passes the DeepSource GitHub Actions workflow (refer to comment below).
- [x] The PR passes Test and Lint GitHub Actions workflows. (refer to comment below)

If some items are not checked, mark your PR as draft (Look for "Still in progress? Convert to Draft" on your PR) . Only mark the PR as "Ready for review" if all the items above are checked.

If you do not know how to address some items, reach out to a maintainer by requesting reviewers.

If some items cannot be addressed, explain the reason in the Description of your PR, and mark the PR ready for review

## Issue

[Issue 107](https://github.com/compSPI/simSPI/issues/107)

### CODE REVIEW

**Comment by ninamiolane** [comment]
@bogdantoader thank you for this great PR! Can you follow the PR checklist above?

For example, the tests need to pass (see Test / build (pull request) above) before we can mark it for review. --> I will mark the PR as draft in the meantime.

many thanks!

**Comment by bogdantoader** [comment]
@ninamiolane Apologies, I was aware the notebook test was failing when we finished on Friday and in the meantime I managed to get it to work on my laptop. I’ll push the working version when I’m back in the office tomorrow

@sonyahanson are you running the notebook in the simSPI anaconda environment and did you run “pip install -e .” on each of the 3 repositories? I wonder if that’s why it can’t see the module and also maybe it’a using a different version of pickle than the one in the environment file. I’ll take a closer look at this tomorrow as well!

**Comment by bogdantoader** [comment]
Not sure why the test coverage is lower - the "impacted file" tem.py is not touched by these changes

**Review by ninamiolane — APPROVED** [review]
Very nice, thank you for this addition! LGTM.

**Pull request merged**
