### PR TITLE
projector module with the right dependencies

### PR DESCRIPTION
**Pull request by harshit-gupta-cor**
Note: This PR can be safely reviewed. It passes the unit tests. The checks fail due to an issue unrelated to this PR which will soon be corrected (see [here](https://github.com/compSPI/simSPI/pull/47#issuecomment-1020343888)). 

This PR follows PRs #20, #23, and #36.
PR #20 asked for smaller PRs (see discussion).
PR #23, #36 were not merged and were closed.  They were not passing the unit tests and needed to point to the updated commit of the base branch. 
This PR points to the correct commit of the base branch (i.e. with the right updated environment.yml package).

The comments from the PR #20 have been incorporated except two (reasons why they have not been incorporated have been given at the comment location).

### CODE REVIEW

**Review by ninamiolane — APPROVED** [review]
Fantastic, thanks! My only comment: projector_utils.py should be renamed to projector.py because:
- _utils is (almost) never useful, it does not bring any information of what is in the file
- it is good practice to have a match of names between: the module name, the main class in the module, and the test file (it is an easier API to remember from a user's perspective).

Other than this NIT, perfect!

**Comment by ninamiolane** [comment]
Oh, but unit-tests need to pass (PR #47  has been merged, thus it should work?)

**Comment by harshit-gupta-cor** [comment]
Renamed the files. The tests are passing on my machine and the checks are failing due to an issue unrelated to this PR which Fred told me will soon be corrected. 
image

**Comment by ninamiolane** [comment]
Excellent! We'll refrain from merging, and wait for this issue to be corrected then. Thanks! 🙌

**Review by geoffwoollard — APPROVED** [review]

**Comment by geoffwoollard** [comment]
Ready when Nina is ready

**Comment by ninamiolane** [comment]
Since @fredericpoitevin solved the issue related to the unit-tests, do you know if this PR can now pass the tests?

**Comment by harshit-gupta-cor** [comment]
@ninamiolane  all the checks pass. It can be merged now.

**Review by ninamiolane — APPROVED** [review]
Thanks! And special thanks to @fredericpoitevin too!

**Pull request merged**
