### PR TITLE
Adding usage tutorial and files related to it

### PR DESCRIPTION
**Pull request by luis-sribeiro**
First version of a tutorial to show some of the available functionalities.

### CODE REVIEW

**Review by ninamiolane — CHANGES_REQUESTED** [review]
Very nice! Thank you very much for this clean code and very helpful tutorial. Some elements havee not been understood about the linear simulator --- but this is definitely the fault of our design (@harshit-gupta-cor @geoffwoollard @fredericpoitevin we should take this into account when we talked about the re-design).

I have put a few comments in the code, but at a high-level:
1. the CI tests need to pass. 

**Linting**: Unfortunately, the linting did not pass. see here: https://github.com/compSPI/simSPI/runs/4993486215?check_suite_focus=true . I think this is because our linter black just got an update (i.e. totally not your fault, you also did not touch these files). To solve this, you can run `black .` from your command line.
```
Run black . --check
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install black[jupyter]``
would reformat tests/test_fov.py
would reformat simSPI/transfer.py

Oh no! 💥 💔 💥
2 files would be reformatted, 15 files would be left unchanged.
Error: Process completed with exit code 1.
```

**Testing**: I wonder why the tests do not pass. Maybe rebase/merge with master and see if these persist?

2. We need to test this notebook within the library. For this, you can add a test_file, that would be called `test_notebooks.py` and use something like this code:

https://github.com/geomstats/geomstats/blob/master/tests/test_notebooks.py

3. Fred and I did some refactoring in ioSPI. If something fails, this might be due to us.

Thanks for this great PR! 🎉

**Comment by luis-sribeiro** [comment]
> Very nice! Thank you very much for this clean code and very helpful tutorial. Some elements havee not been understood about the linear simulator --- but this is definitely the fault of our design (@harshit-gupta-cor @geoffwoollard @fredericpoitevin we should take this into account when we talked about the re-design).
> 
> I have put a few comments in the code, but at a high-level:
> 
> 1. the CI tests need to pass.
> 
> **Linting**: Unfortunately, the linting did not pass. see here: https://github.com/compSPI/simSPI/runs/4993486215?check_suite_focus=true . I think this is because our linter black just got an update (i.e. totally not your fault, you also did not touch these files). To solve this, you can run `black .` from your command line.
> 
> ```
> Run black . --check
> Skipping .ipynb files as Jupyter dependencies are not installed.
> You can fix this by running ``pip install black[jupyter]``
> would reformat tests/test_fov.py
> would reformat simSPI/transfer.py
> 
> Oh no! 💥 💔 💥
> 2 files would be reformatted, 15 files would be left unchanged.
> Error: Process completed with exit code 1.
> ```
> 
> **Testing**: I wonder why the tests do not pass. Maybe rebase/merge with master and see if these persist?
> 
> 2. We need to test this notebook within the library. For this, you can add a test_file, that would be called `test_notebooks.py` and use something like this code:
> 
> https://github.com/geomstats/geomstats/blob/master/tests/test_notebooks.py
> 
> 3. Fred and I did some refactoring in ioSPI. If something fails, this might be due to us.
> 
> Thanks for this great PR! 🎉

Great. I will make the changes, and thank you so much for the feedback. Regarding the Linear Simulator, I actually was planning to add noise and shift as well (in the image formation section). But indeed, I was wondering why there was a separate module called Linear simulator with those functionalities. I just would like to point it out that maybe someone who is more familiar with SPI would not be confused about this. Just one more thing, I was doing some tests with the multislice module to add to the tutorial as well, and it was the first time I encountered the expression "complex contrast transfer function". Do you have any resources about that?

**Comment by fredericpoitevin** [comment]
HI @luis-sribeiro thanks a lot for all your feedback and contributions!

About the contrast transfer function:
in optics, no system is "perfect" in the sense that the image of a point source will never be a point, the lenses etc will "blur" it into something that looks like a point but maybe a bit more spread. This effect is captured by a function called the "point-spread function" (PSF) of the optics apparatus used.
If you image something that is not a point, this "blurring effect" is still there, and the resulting image will be the perfect image convolved with the PSF.
Convolutions are easier to handle in Fourier space (see [Convolution theorem](https://en.wikipedia.org/wiki/Convolution_theorem)), where the output image is just the product of the original image and the Fourier transform of the PSF, which is called the Contrast Transfer Function (see this [wikipedia page about it](https://en.wikipedia.org/wiki/Convolution_theorem)). 
Generally, the CTF is a complex quantity.

**Comment by luis-sribeiro** [comment]
> HI @luis-sribeiro thanks a lot for all your feedback and contributions!
> 
> About the contrast transfer function: in optics, no system is "perfect" in the sense that the image of a point source will never be a point, the lenses etc will "blur" it into something that looks like a point but maybe a bit more spread. This effect is captured by a function called the "point-spread function" (PSF) of the optics apparatus used. If you image something that is not a point, this "blurring effect" is still there, and the resulting image will be the perfect image convolved with the PSF. Convolutions are easier to handle in Fourier space (see [Convolution theorem](https://en.wikipedia.org/wiki/Convolution_theorem)), where the output image is just the product of the original image and the Fourier transform of the PSF, which is called the Contrast Transfer Function (see this [wikipedia page about it](https://en.wikipedia.org/wiki/Convolution_theorem)). Generally, the CTF is a complex quantity.

Thanks for the nice explanation. What got me confused was the explicit use of the term "complex", it was the first time I saw the cft being referred to as complex ctf. So I wanted to make sure if I was missing something or not.

**Comment by ninamiolane** [comment]
@luis-sribeiro thank you so much for catching this! I have raised an issue on the ioSPI repository. Would you mind addressing the problem in the code there? https://github.com/compSPI/ioSPI/issues/47

Additionally, I should let you know that ioSPI is undergoing some refactoring --- which might become cumbersome for you because this is going to mean so name changes :/ Sorry for this! I'd say the sooner we can merge this the better, so that the next PRs are only changes of names.

**Comment by ninamiolane** [comment]
@luis-sribeiro should work now, can you try again?

**Comment by luis-sribeiro** [comment]
> @luis-sribeiro should work now, can you try again?

Sure. I will just make the name changes and pull, and then I believe it will work.

**Comment by luis-sribeiro** [comment]
> @ninamiolane @fredericpoitevin Hi! I was looking at the tests, and one that failed is related to the `write_crd_file` function. I believe this function has a little problem (that I corrected in my PR). If you look at the `for` loops in this function, we have **n_particles^2** iterations in total instead of **n_particles** iterations. So, the coordinate file will have additional lines that will be ignored. And because of the inner `for` loop, the particles are created in the same positions, but with different rotations, which basically generates a micrograph with a single particle image (they are all overlapped on top of each other).
> 
> * What the function is generating: https://pastebin.com/wa8GfNRd
> * What it should generate: https://pastebin.com/bge6aKhH

@ninamiolane @fredericpoitevin Could you take a look at the test for the crd.py file? I belive my correction for the `write_crd_file` function makes sense, but it is not passing the tests.

**Comment by fredericpoitevin** [comment]
Hi @luis-sribeiro I think it all looks good! @ninamiolane the "Building simSPI Container" check is not passing but that's the same credential problem I need to take care of (hopefully soon!). 
What matters is that the "Lint", "Test" and "Deepsource" checks pass, which they do. So I'd be in favor of starting the code review process.

**Comment by ninamiolane** [comment]
@fredericpoitevin @luis-sribeiro do you think that it could be possible to have this notebook (or a faster version of it) tested as part of the GitHub workflow. Example code to test notebooks is here: https://github.com/geomstats/geomstats/blob/master/tests/test_notebooks.py.

Two things that need to happen to do this:
- the notebook should be less than 3min in execution (otherwise everybody will go crazy during the PRs)
- it should be able to run within the container.

If we do not test the notebooks, then we will forget to update them during the refactoring of simSPI, and they will become outdated very soon. Thanks!

**Comment by fredericpoitevin** [comment]
<p>Indeed it looks like there is a strong aliasing effect in the CTF image. A great resource to play with image and CTF parameters and get a feel of aliasing conditions is: https://3dem.github.io/relion/ctf.html</p><p> </p><p>I'd suggest finding a better set of parameters that does not give rise to aliasing.</p><p> </p><p> </p><p>Also, it is indeed true that the starting particle image from TEM simulator already had CTF applied to it, as can be seen from the Thon rings in the middle image.</p><p> </p><p>I'd suggest using the linear_simulator from scratch, not from an output from TEM simulator.</p>

---

 <a href='https://app.reviewnb.com/compSPI/simSPI/pull/57/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by fredericpoitevin** [comment]
<p>I think this is an opportunity to discuss "realistic" non-aliasing conditions as a function of defocus value, pixel size, etc.</p><p> </p><p>It would be very informative.</p><p> </p><p>Wiener filtering is interesting but I am afraid this is more work than just adding a simple paragraph. Let's keep the scope of this notebook about the simulators.</p>

---

 <a href='https://app.reviewnb.com/compSPI/simSPI/pull/57/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by luis-sribeiro** [comment]
@ninamiolane @fredericpoitevin  @geoffwoollard Thank you so much for the feedback. I will make the changes and update the PR.

**Comment by geoffwoollard** [comment]
<p>That's a great point. This is a notebook about simulation, not just about the tem_simulator simulator.</p>

---

 <a href='https://app.reviewnb.com/compSPI/simSPI/pull/57/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by geoffwoollard** [comment]
<p>Great idea. Yeah, good point of the Wiener filter opening up a box of worms. Once some functions are made for that it can be added in its own notebook down the road..</p><p> </p><p>If you end up doing as Fred suggests, you also vary the number of pixels (for fixed pixel size and defocus)</p>

---

 <a href='https://app.reviewnb.com/compSPI/simSPI/pull/57/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by geoffwoollard** [comment]
<p>It blew my mind when I first heard it. I thought adding white Gaussian noise in real space would be "high frequency noise" and die out at low frequency...</p><p> </p><p>Some SNR refs to reference are. </p><p> </p><p>It might make more sense to refer to these down the road when the camera parameters of the tem simulator are demonstrated, because right now it assumes a "perfect detector". Anyways I put them in here now for completion. (They are from https://github.com/geoffwoollard/learn_cryoem_math)</p><ul><li>Ruskin, R. S., Yu, Z., &amp; Grigorieff, N. (2013). Quantitative characterization of electron detectors for transmission electron microscopy. Journal of Structural Biology, 184(3), 385–393.&nbsp;<a href="http://doi.org/10.1016/j.jsb.2013.10.016" target="_blank">http://doi.org/10.1016/j.jsb.2013.10.016</a></li><li class="ql-indent-1">Details on how to experimentally measure the DQE for different detectors (CMOS, CCD, film). Mathematical details about modulation transfer function, noise poser spectrum, signal to noise ratio</li><li>Meyer, R. R., &amp; Kirkland, A. (1998). The effects of electron and photon scattering on signal and noise transfer properties of scintillators in CCD cameras used for electron detection. Ultramicroscopy, 75(1), 23–33.&nbsp;<a href="http://doi.org/10.1016/S0304-3991(98)00051-5" target="_blank">http://doi.org/10.1016/S0304-3991(98)00051-5</a></li><li>Baxter, W. T., Grassucci, R. A., Gao, H., &amp; Frank, J. (2009). Determination of signal-to-noise ratios and spectral SNRs in cryo-EM low-dose imaging of molecules. Journal of Structural Biology, 166(2), 126–132.&nbsp;<a href="http://doi.org/10.1016/j.jsb.2009.02.012" target="_blank">http://doi.org/10.1016/j.jsb.2009.02.012</a></li><li>McMullan, G., Chen, S., Henderson, R., &amp; Faruqi, A. R. (2009). Detective quantum efficiency of electron area detectors in electron microscopy. Ultramicroscopy, 109(9), 1126–1143.&nbsp;<a href="http://doi.org/10.1016/j.ultramic.2009.04.002" target="_blank">http://doi.org/10.1016/j.ultramic.2009.04.002</a></li><li class="ql-indent-1">Rigerous and pedagogical (and not too long) overview of how to measure modulation transfer function (MTF), noise power spectrum (NPS), detective quantum efficiency (DQE) from images (knife method). Analytical results for edge spread function, line spread function given which are derived/presented in more detail in references (textbooks, etc); see equations 10-13. special care is taken for DQE(w=0), because there is much noise in the NPS at low spatial frequency and the MTF can drop off quickly at low spatial frequency. Methods to measure the NPS from the difference of digitized frames is presented. All this theory is used to compare film, CCD, Medipix2 (hybrid pixel detector) and a MAPS (monolithic active pixel sensor) detector. For detectors (such as MAPS) that can distinguish individual electron events, one can calculate the DQE from the probability density of the energy (Landau plot), although this density is hard to estimate. The authors do Monte Carlo simulations at two levels of theory (“continuous slowing down approximation”, and another they call “Full Monte Carlo” that treats both elastic and inelastic collisions as stochastic), and give references to a previous study and a textbook. Using this theory they simulate electron trajectories, deposited energy, and the resulting image in film, and MAPS. They are then able connect detector performance (DQE, etc) to physical/causal explanations, and suggest how to make the ideal detector. History has vindicated their calls for how to make a detector of choice.</li><li>Grob, P., Bean, D., Typke, D., Li, X., Nogales, E., &amp; Glaeser, R. M. (2013). Ranking TEM cameras by their response to electron shot noise. Ultramicroscopy, 133, 1–7.&nbsp;<a href="http://doi.org/10.1016/j.ultramic.2013.01.003" target="_blank">http://doi.org/10.1016/j.ultramic.2013.01.003</a></li><li class="ql-indent-1">Details mathematical analysis of detector noise, based on minimal assumptions (poisson stats of the number of general random variable events for the count registered, with mean and std given). See supplementary info for detailed proofs.</li><li><br></li></ul><p> </p>

---

 <a href='https://app.reviewnb.com/compSPI/simSPI/pull/57/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
