### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by thisTyler**
Refactored ioSPI to conform with Nina's requests as much as possible. This has consequences of that refactor.

# Will show errors until https://github.com/compSPI/ioSPI/pull/46 is merged

### CODE REVIEW

**Comment by ninamiolane** [comment]
Also address the lint error (see my comment on https://github.com/compSPI/ioSPI/pull/46)

Thanks!

**Comment by fredericpoitevin** [comment]
closes #75

**Comment by fredericpoitevin** [comment]
@thisTyler progress was made. The only remaining error (the same thrown several times) is:
```
==================================== ERRORS ====================================
_________________ ERROR at setup of test_get_config_from_yaml __________________

    @pytest.fixture
    def sample_class():
        """Instantiate TEMSimulator for testing."""
        test_files_path = "/work/tests/test_files"
        tmp_path = test_files_path
        cwd = os.getcwd()
    
>       tem_simulator = tem.TEMSimulator(
            str(Path(cwd, test_files_path, "path_config.yaml")),
            str(Path(cwd, test_files_path, "sim_config.yaml")),
        )

tests/test_tem.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <simSPI.tem.TEMSimulator object at 0x7f1bca0f5460>
path_config = '/work/tests/test_files/path_config.yaml'
sim_config = '/work/tests/test_files/sim_config.yaml'

    def __init__(self, path_config, sim_config):
    
        with open(path_config, "r") as stream:
            parsed_path_config = yaml.safe_load(stream)
    
>       self.output_path_dict = self.generate_path_dict(**parsed_path_config)
E       TypeError: generate_path_dict() got an unexpected keyword argument 'local_sim_dir'

simSPI/tem.py:31: TypeError
```

Can you look into this? Don't forget to pull your local "refactoring" branch before starting the fix.

**Comment by thisTyler** [comment]
@fredericpoitevin sure, I'll look into it tomorrow. Thank you for the help!

**Comment by thisTyler** [comment]
@fredericpoitevin the issue on my end has been fixed - back to import errors unfortunately. Thanks again for helping out with this.

**Pull request merged**
