### PR TITLE
projector module on the correct commit of the base branch

### PR DESCRIPTION
**Pull request by harshit-gupta-cor**
This PR follows  PRs #20 and #23. 
PR #20 asked for smaller PRs (see [discussion](https://github.com/compSPI/simSPI/pull/20#issuecomment-983853121)).  PR #23 was not merged and was closed since it was pointing to the previous commit of the base branch. This was making it fail the unit tests. 
This PR points to the correct commit of the base branch (i.e. with the right updated environment.yml package).

The comments from the previous PRs have been incorporated except two (reasons why they have not been incorporated have been given at the comment location).

### CODE REVIEW

**Comment by harshit-gupta-cor** [comment]
Issue #38 raised for the test failing.

**Comment by fredericpoitevin** [comment]
Building fails because pre-built binaries on Linux can be installed from conda only, while `pip` works on Mac - for full details, see: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#installing-prebuilt-binaries-for-pytorch3d

**Comment by harshit-gupta-cor** [comment]
I created PR #45 to update environment.yml accordingly. Although now it install pytorch3d on linux machine but has problem with mac. Still figuring it out.

**Comment by fredericpoitevin** [comment]
OK let's discuss in that other PR and merge this one only after this problem is addressed in#45.

The fix you propose will not work. Let's discuss there.

**Comment by harshit-gupta-cor** [comment]
This PR points to the previous commit of the base branch and therefore doesn't pass the unit tests. This has been followed by #53.

**Pull request closed without merging**
