### PR TITLE
Importing iospi into simspi and transfer.py into simspi

### PR DESCRIPTION
**Pull request by geoffwoollard**
Importing iospi into simspi https://github.com/geoffwoollard/simSPI/commit/71f58af05aaea284a0a99a0623669672f59d59bb

### CODE REVIEW

**Comment by geoffwoollard** [comment]
Linting and testing is getting this far

```
Successfully built ioSPI
Installing collected packages: wcwidth, setuptools-scm, blessed, scipy, flyingcircus-numeric, flyingcircus, raster-geometry, ioSPI
Successfully installed blessed-1.18.1 flyingcircus-0.1.4.0 flyingcircus-numeric-0.1.1.2 ioSPI-0.0.1 raster-geometry-0.1.4.1 scipy-1.7.1 setuptools-scm-6.0.1 wcwidth-0.2.5

done
#
# To activate this environment, use
#
#     $ conda activate base
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/runner/work/simSPI/simSPI
Error: Process completed with exit code 1.
```

**Comment by geoffwoollard** [comment]
FYI I put myself down as maintainer in `setup.py`

**Comment by geoffwoollard** [comment]
There is some issue with flake thinking black needs to change things. I think it's a line length issue. But I thought the default we were going for was 79 characters. I used this for (`black ... -l 79`) and passed deepsource. But then things failed during linting

```
Run $CONDA/bin/flake8 simSPI tests
  $CONDA/bin/flake8 simSPI tests
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib
simSPI:0:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'simSPI'
tests/test_multislice.py:16:37: BLK100 Black would make changes.
Error: Process completed with exit code 1.
```

This is a known issue: https://github.com/houndci/hound/issues/1769

@ninamiolane ?

**Comment by geoffwoollard** [comment]
Yes, the issue is definitely black and flake8 consistency. The missing directory issue went away.

```

Run $CONDA/bin/flake8 src tests
src/multislice.py:23:17: BLK100 Black would make changes.
tests/test_multislice.py:16:37: BLK100 Black would make changes.
Error: Process completed with exit code 1.
```

I checked the files it references, and perhaps its ending on `(` or the indentation on the next line...

https://github.com/geoffwoollard/simSPI/blob/multi_slice/src/multislice.py#L23
https://github.com/geoffwoollard/simSPI/blob/multi_slice/tests/test_multislice.py#L16

**Comment by geoffwoollard** [comment]
The simSPI.yml has

```
dependencies:
  - flake8-black
  - numba
  - numpy
  - pip
  - pyfftw
  - pytest
  - pytest-cov
  - pip:
    - git+https://github.com/geoffwoollard/ioSPI.git@move_functions_from_compspi
    - raster_geometry
```

Is this counting pip twice?

**Comment by geoffwoollard** [comment]
@ninamiolane @fredericpoitevin `test_sim_volumes.py` is failing tests. It was there from before and I didn't write it, nor the sim_volumes.py it tests. What should I do with it? Move them to a sim_volumes branch?

**Comment by geoffwoollard** [comment]
Ok I moved transfer into simSPI. It's passing all the tests. I'm using a place holder for importing ioSPI for now in the simSPI.yml a la https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch. 

But when the ioSPI is merged into master and I can get fourier from there (by making a one line change to the yml to refer to compSPI/ioSPI). I'll just undo https://github.com/geoffwoollard/simSPI/commit/9f981d0d92ce68fe7f8aefcd6234c5d2537be726

**Comment by fredericpoitevin** [comment]
@geoffwoollard I'll look back here once your PR on ioSPI has been merged. Will be easier to test dependency to it.

**Comment by geoffwoollard** [comment]
> @geoffwoollard I'll look back here once your PR on ioSPI has been merged. Will be easier to test dependency to it.

Ok ioSPI has been merged

**Comment by geoffwoollard** [comment]
@fredericpoitevin Have a look

**Pull request merged**
